#!/bin/bash

# This script rebuilds the algorithmically-generated ftml files.

set -e

if [ ! -f wscript ]
then
	echo "Must be in the root of the project"
	exit 2
fi

# configure tests
tests="AllChars Kern Matras"
urls='url(../references/Nokyung-Regular.ttf)=RefR url(../references/Nokyung-Bold.ttf)=RefB url(../results/Nokyung-Regular.ttf)=R url(../results/Nokyung-Bold.ttf)=B url(../references/DaiBannaSIL-Light.ttf)=DaiBanna url(../references/NotoSansNewTaiLue-Regular.ttf)=Noto'
ufo='source/masters/Nokyung-Regular.ufo'

# list all the fonts to test
fonts=''
for url in $urls
do
	fonts="$fonts -s '$url'"
done

echo "Rebuilding ftml files..."
for test in $tests
do
	base=${test,,}
	title="\"${test} auto\""
	ftml=tests/${base}.ftml
	log=tests/logs/${base}.log
	eval tools/psfgenftml.py -q -t "$title" --norendercheck --scale 200 -i source/glyph_data.csv --xsl ../tools/ftml.xsl --prevfont references/Nokyung-Regular.ttf "$fonts" -l $log $ufo $ftml &
done
wait
echo "done."
