#!/bin/sh

# This normalization will also run check and fix routines
psfnormalize -p checkfix=fix source/masters/Nokyung-Regular.ufo -l source/masters/logs/normR.log
psfnormalize -p checkfix=fix source/masters/Nokyung-Bold.ufo  -l source/masters/logs/normB.log

# Building composites - needs to be done after normalization or may complain due to bad anchor coordinates
psfbuildcomp -c -i source/composites.txt source/masters/Nokyung-Regular.ufo -l source/masters/logs/compsR.log
psfbuildcomp -c -i source/composites.txt source/masters/Nokyung-Bold.ufo -l source/masters/logs/compsB.log

psfsetpsnames -i source/glyph_data.csv source/masters/Nokyung-Regular.ufo -l source/logs/psnames.log
psfsetglyphorder --header sort_final -i source/glyph_data.csv source/masters/Nokyung-Regular.ufo -l source/masters/logs/sortorder.log

# Following sync will copy psnames and glyphorder updates to all fonts
psfsyncmasters source/Nokyung.designspace -l source/masters/logs/sync.log

# Create WOFF metadata file
psfmakewoffmetadata -n "Nokyung" -i "org.sil.fonts" -o source/Nokyung-WOFF-metadata.xml source/masters/Nokyung-Regular.ufo

# Update FEA in UFO
psfmakefea -o source/masters/Nokyung-Regular.ufo/features.fea   -i source/main.feax source/masters/Nokyung-Regular.ufo   &
psfmakefea -o source/masters/Nokyung-Bold.ufo/features.fea -i source/main.feax source/masters/Nokyung-Bold.ufo &
wait
